### PR TITLE
Add terraform IaC for osd-network-verifier example/quick testing

### PR DESCRIPTION
**Pull request by judexzhu**
- Enhancement/Feature

## What does this PR do? / Related Issues / Jira
Use Terraform IaC to provide an alternative way to quick establish a VPC with or without a firewall for osd-network-verifier testing.

This Terraform script sets up a network infrastructure in the AWS Cloud. The infrastructure includes a Virtual Private Cloud (VPC), subnets, a network firewall(optional), and an Internet Gateway.

1. **VPC:** The script creates a VPC in the specified AWS region. 

2. **Subnets:** Three subnets are created within the VPC - a public subnet, a private subnet, and a firewall subnet. Each subnet is created in the specified availability zone with its respective CIDR block.

3. **Internet Gateway:** An Internet Gateway is created and attached to the VPC. This allows the VPC to communicate with the Internet.

4. **Network Firewall(optional):** A network firewall is set up for the VPC. The firewall is associated with the firewall subnet. The firewall has a policy and a rule group. The policy defines the stateless actions to take for packets. The rule group contains a list of domains to block.

5. **NAT Gateway:** A NAT Gateway is created in the public subnet. This allows instances in the private subnet to connect to the internet or other AWS services.

6. **Routing:** Route tables and associations are created for the subnets. The public and firewall subnets are associated with the Internet Gateway, allowing them to communicate directly with the Internet. The private subnet is associated with the NAT Gateway, allowing it to access the Internet via the NAT Gateway.

The script outputs the IDs of the created VPC and subnets. 

## Checklist

- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have tested the functionality against aws, it doesn't cause any regression
- [x] I have added execution results to the PR's readme

### CODE REVIEW

**Comment by abyrne55** [comment]
/label tide/merge-method-squash

I've tested both the firewalled and firewall-less terraform script, and they worked quite nicely. Good work @judexzhu! 

Would you mind just adding a reference to these scripts into the main README (at the root of the repo)?

**Comment by judexzhu** [comment]
Add Terraform Scripts section in `main/README.md`, please help to review

**Review by abyrne55 — APPROVED** [review]
/lgtm
/approve

Thanks @judexzhu!

**Comment by fahlmant** [comment]
There's some overlap with the code in https://github.com/openshift/osd-network-verifier/tree/main/examples/aws/firewall, should that be removed?

**Comment by judexzhu** [comment]
@fahlmant This is one reason I came to the idea of this terraform PR, for `firewall.go` does include a cleanup feature, which might take a lot of effort if we like to change some settings or do the cleanup job after testing.

These can be resolved with Terraform and it's variables settings

**Comment by mjlshen** [comment]
This does overlap with https://github.com/openshift/osd-network-verifier/blob/bb8056c1f9105672ef135f7dceefb01d174e9c7c/integration/main.go#L25-L26 which can be used to setup a VPC, Firewall, etc and teardown manually

When `-create-only` / `-delete-only` are not used, the integration test just creates all the AWS infra and deletes it automatically at the end of the test - this Terraform looks ok to me, so not looking to hold this PR, but more trying to understand if it's really needed. I'm +1 to removing the example code either way

**Comment by dakotalongRH** [comment]
To bring this back to life - recently I needed to do testing with a VPC + firewall setup and the integration tools is quite tedious compared to this PR.  By default the integration tool will spin up a VPC + firewall with a limit of 1 blocked endpoint, run onv, and then delete the resources.  To make changes it requires a lot more changes to the actual code whereas using the Terraform script allows to easily change them on the fly.  The customization of firewall aspects is much more streamlined and I'm +1 to merging this and using it as our main tool.

**Comment by abyrne55** [comment]
/approve
😌

**Pull request merged**
