### PR TITLE
feat: use standardized errors for the output

### PR DESCRIPTION
**Pull request by boranx**
Fix: https://issues.redhat.com/browse/OSD-10574

**Example Executions**:

_against a subnet without an igw_

```shell
AWS_ACCESS_KEY_ID=XX AWS_SECRET_ACCESS_KEY=XXX ./osd-network-verifier egress --subnet-id subnet-00370fcf033c27bd8 --region us-east-1
Using region: us-east-1
Created instance with ID: i-00e3fadaefc6342f0
EC2 Instance: i-00e3fadaefc6342f0 Running
Gathering and parsing console log output...
Terminating ec2 instance with id i-00e3fadaefc6342f0
Summary:
printing out failures:
printing out exceptions preventing onv from running:
 -  egressURL error: [   28.639978] cloud-init[2256]: Cannot find a valid baseurl for repo: amzn2-core/2/x86_64
 -  egressURL error: [   28.640090] cloud-init[2256]: Could not retrieve mirrorlist https://amazonlinux-2-repos-us-east-1.s3.dualstack.us-east-1.amazonaws.com/2/core/latest/x86_64/mirror.list error was
 -  egressURL error: [   28.640192] cloud-init[2256]: 12: Timeout on https://amazonlinux-2-repos-us-east-1.s3.dualstack.us-east-1.amazonaws.com/2/core/latest/x86_64/mirror.list: (28, 'Failed to connect to amazonlinux-2-repos-us-east-1.s3.dualstack.us-east-1.amazonaws.com port 443: Connection timed out')
 -  egressURL error: [   48.093067] cloud-init[2256]: Cannot find a valid baseurl for repo: amzn2-core/2/x86_64
 -  egressURL error: [   48.093463] cloud-init[2256]: Could not retrieve mirrorlist https://amazonlinux-2-repos-us-east-1.s3.dualstack.us-east-1.amazonaws.com/2/core/latest/x86_64/mirror.list error was
 -  egressURL error: [   48.093592] cloud-init[2256]: 12: Timeout on https://amazonlinux-2-repos-us-east-1.s3.dualstack.us-east-1.amazonaws.com/2/core/latest/x86_64/mirror.list: (28, 'Failed to connect to amazonlinux-2-repos-us-east-1.s3.dualstack.us-east-1.amazonaws.com port 443: Connection timed out')
 -  egressURL error: [   48.104653] cloud-init[2256]: Apr 08 15:21:55 cloud-init[2256]: util.py[WARNING]: Failed to install packages: ['docker']
 -  egressURL error: [   48.703765] cloud-init[2462]: Failed to start docker.service: Unit not found.
 -  egressURL error: [   48.715777] cloud-init[2462]: sudo: docker: command not found
 -  egressURL error: [   48.724098] cloud-init[2462]: sudo: docker: command not found
printing out errors faced during the execution:
Failure!
```

_validation failure_

```shell
AWS_ACCESS_KEY_ID=XX AWS_SECRET_ACCESS_KEY=XXX ./osd-network-verifier egress --subnet-id subnet-030455abded968aa2 --region us-east-1
Using region: us-east-1
Created instance with ID: i-0dca7346bf3df1ff3
EC2 Instance: i-0dca7346bf3df1ff3 Running
Gathering and parsing console log output...
Terminating ec2 instance with id i-0dca7346bf3df1ff3
Summary:
printing out failures:
 -  egressURL error: Unable to reach nosnch.in:443
printing out exceptions preventing onv from running:
printing out errors faced during the execution:
Failure!
```

### CODE REVIEW

**Review by fahlmant — COMMENTED** [review]
I don't think we should remove failures and exceptions if we don't have to. The ask here is to do something more like this

```
type GenericError error
type EgressURLError error
type DNSError error
type VPCError error
...
And then the consuming code can handle the error and return message however they want
```

**Comment by boranx** [comment]
@fahlmant would you mind re-review it? I've updated here as no change to failures, exceptions, errors but there are the defined errors we can use

**Review by fahlmant — APPROVED** [review]
/approve

**Pull request merged**
