### PR TITLE
copy URL lists from golden-ami repo

### PR DESCRIPTION
**Pull request by eth1030**
- Enhancement/Feature

## What does this PR do? / Related Issues / Jira
add egress URL lists to verifier repo

[OSD-22627](https://issues.redhat.com//browse/OSD-22627)

### CODE REVIEW

**Comment by eth1030** [comment]
@fahlmant Don't know what config.yaml is for, but it existed in the golden-ami repo. Wanted to keep it consistent.

**Review by fahlmant — APPROVED** [review]
/approve

**Pull request merged**
