### PR TITLE
Update boilerplate, fix linting issues

### PR DESCRIPTION
**Pull request by joshbranham**
## What does this PR do? / Related Issues / Jira

- Run `make boilerplate-update` to get the latest boilerplate.
- Also removed Linh who is no longer on SRE.
- Resolve any linting issues that came up.

I ran a verification using a custom egress list URL to make sure the updated code (as a result of the linter) works
```
> ./osd-network-verifier egress --subnet-id subnet-0bab965a3722b750d --egress-list-location https://raw.githubusercontent.com/openshift/osd-network-verifier/refs/heads/main/pkg/data/egress_lists/aws-classic.yaml --profile devaccount --region us-west-2
Using region: us-west-2
Using external egress list from https://raw.githubusercontent.com/openshift/osd-network-verifier/refs/heads/main/pkg/data/egress_lists/aws-classic.yaml
Created security group with ID: sg-0c3dd5d14693b28cd
Created instance with ID: i-01809a6716306719a
Deleting instance with ID: i-01809a6716306719a
Deleting security group with ID: sg-0c3dd5d14693b28cd
Summary:
All tests passed!
Success
```

## Checklist

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have tested the functionality against gcp / aws, it doesn't cause any regression
- [ ] I have added execution results to the PR's readme

## Reviewer's Checklist

- [ ] (This needs to be done after technical review) I've run the branch on my local, verified that the functionality is ok

### CODE REVIEW

**Comment by joshbranham** [comment]
Wrapping up linting failures, the linter config was updated so I get to fix things :)

**Comment by abyrne55** [comment]
Tested locally (incl. remote list downloading feature). Thanks for clearing away a lot of cruft @joshbranham 

/approve

**Pull request merged**
