### PR TITLE
Add Terraform script for GCP Testing

### PR DESCRIPTION
**Pull request by eth1030**
This PR contains a Terraform script that automates the process of setting up a VPC in GCP, creating public and private subnets, cloud NAT for the private subnet, and a firewall that blocks certain domains for testing the network verifier on GCP as part of [OSD-24919](https://issues.redhat.com/browse/OSD-24919)

## Checklist

- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have tested the functionality against gcp / aws, it doesn't cause any regression
- [ ] I have added execution results to the PR's readme

## Reviewer's Checklist

- [ ] (This needs to be done after technical review) I've run the branch on my local, verified that the functionality is ok

## How to test this PR locally / Special Instructions
```
terraform init
terraform apply
./osd-network-verifier/osd-network-verifier egress --platform gcp-classic --subnet-id <public-subnet-name> --vpc-name <vpc-name>
terraform destroy
```

## Logs 
Expected output: verifier identifies an egressURL error for blocked essential domains. These domains can be specified in `terraform.tfvars` or as default `quay.io` and `cdn01.quay.io` are blocked.
```
Using Project ID <YOUR_PROJECT_ID>
Created instance with ID: verifier-xxxx
Applying labels
Successfully applied labels 
ComputeService Instance: verifier-xxxx RUNNING
Gathering and parsing console log output...
Summary:
printing out failures:
 - egressURL error: https://events.amazonaws.com:443 (Could not resolve host: events.amazonaws.com)
 - egressURL error: https://cdn01.quay.io:443 (Failed to connect to cdn01.quay.io port 443: Connection timed out)
 - egressURL error: https://quay.io:443 (Failed to connect to quay.io port 443: Connection timed out)

printing out exceptions preventing the verifier from running the specific test:
printing out errors faced during the execution:
Failure!
```

### CODE REVIEW

**Comment by AlexVulaj** [comment]
/approve

I haven't had time to test but this looks generally good to me.

**Review by abyrne55 — APPROVED** [review]
Tested locally: works beautifully! Great job @eth1030!
/lgtm

**Pull request merged**
