### PR TITLE
OSD-10311 - Adding lint and codecov conventions

### PR DESCRIPTION
**Pull request by bdematte**
Adding the lint and code coverage conventions.
In addition, in allow to not break builds when lint and coverage will be part of the CI, fixing the lint errors.

### CODE REVIEW

**Comment by bdematte** [comment]
/hold
I want to progress on the CI updates to ensure all needed changes in osd-network-verifier are part of this PR

**Review by abyrne55 — APPROVED** [review]
/lgtm

Ran `make lint`, `make coverage`, and `make build` without issues. Also tested built binary's `egress` command and `--help` option. Just running straight `make` with no args gives an error about `No boilerplate-related activity` but I'm assuming that's out of scope for this PR.

**Comment by bdematte** [comment]
The `make` issue has been fixed in https://github.com/openshift/osd-network-verifier/pull/68 but as I did not fetch the latest changes yesterday, checking out the pr isn't pulling the fix hence the issue still appearing.

**Pull request merged**
