### PR TITLE
Update release process docs and AMI images

### PR DESCRIPTION
**Pull request by AlexVulaj**
- Enhancement/Feature

## What does this PR do? / Related Issues / Jira
Updates docs around releasing and also fixes a bug with resource cleanup in integration tests.

## Logs 

Error I was seeing from cleanup:
```
panic: operation error EC2: DeleteVpc, https response error StatusCode: 400, RequestID: 3ee80c4a-badb-415a-9b95-f568cf795270, api error DependencyViolation: The vpc 'vpc-0fa551f9b466b36a6' has dependencies and cannot be deleted.
```

When I went and looked at the VPC in AWS, there was still a security group attached.

### CODE REVIEW

**Comment by AlexVulaj** [comment]
/hold

Going to split this up into two separate PRs

**Review by rafael-azevedo — APPROVED** [review]
/lgtm

**Review by rafael-azevedo — APPROVED** [review]
/lgtm

**Pull request merged**
