### PR TITLE
Added flow diagrams in READMEs for better understanding

### PR DESCRIPTION
**Pull request by ritmun**
Added flow diagrams for better understanding

ref https://coreos.slack.com/archives/CMD1L32M9/p1652352722619129

### CODE REVIEW

**Comment by fahlmant** [comment]
@ritmun Can you please update the PR title to be a bit more descriptive?

**Comment by ritmun** [comment]
> @ritmun Can you please update the PR title to be a bit more descriptive?

done

**Review by fahlmant — APPROVED** [review]
/approve

**Pull request merged**
